remote_mcps:

  - name: "Fetch MCP"
    base_url: "https://fetch-mcp.example.com"
    namespace: "fetch"
    timeout: 30
    retry:
      max_attempts: 3
      initial_delay: 1
      max_delay: 10
    headers:
      User-Agent: "Remote-MCP-Fetcher/1.0"

  - name: "Brave Search MCP"
    base_url: "https://search-mcp.example.com"
    namespace: "search"
    timeout: 30
    retry:
      max_attempts: 3
      initial_delay: 1
      max_delay: 10
    headers:
      User-Agent: "Remote-MCP-Fetcher/1.0"

  - name: "Text Processing MCP"
    base_url: "http://localhost:8003"
    namespace: "text"
    timeout: 5
    retry:
      max_attempts: 3
      initial_delay: 0.1
      max_delay: 1.0
    headers: null

  - name: "Example MCP"
    base_url: "http://localhost:8080"
    namespace: "example"
    timeout: 5
    retry:
      max_attempts: 3
      initial_delay: 0.1
      max_delay: 1.0
    headers: null

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "rmf.log"

server:
  sse_enabled: true
  sse_retry_timeout: 3000
  max_concurrent_requests: 10 