remote_mcps:
  - name: "Text Processing MCP"
    base_url: "http://localhost:8003"
    namespace: "text"
    timeout: 5
    retry:
      max_attempts: 3
      initial_delay: 0.1
      max_delay: 1.0
    headers: null

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "rmf_test.log"

server:
  sse_enabled: true
  sse_retry_timeout: 1000
  max_concurrent_requests: 5 